/**
 * PDF Report Engine
 * Generates downloadable ESG report PDFs
 */

const PDFDocument = require('pdfkit');

/**
 * Adds a section heading to the PDF
 * @param {object} doc - PDFDocument instance
 * @param {string} title - Section title
 */
function addSectionHeading(doc, title) {
  doc.fontSize(14)
     .font('Helvetica-Bold')
     .text(title, { underline: true })
     .moveDown(0.5);
}

/**
 * Adds section content to the PDF
 * @param {object} doc - PDFDocument instance
 * @param {string} content - Section content
 */
function addSectionContent(doc, content) {
  doc.fontSize(11)
     .font('Helvetica')
     .text(content || 'No data available.', { align: 'justify' })
     .moveDown(1.5);
}

/**
 * Adds report header
 * @param {object} doc - PDFDocument instance
 * @param {object} esgReport - ESG report data
 */
function addReportHeader(doc, esgReport) {
  doc.fontSize(20)
     .font('Helvetica-Bold')
     .text('Carbon Intelligence ESG Report', { align: 'center' })
     .moveDown(0.5);

  doc.fontSize(10)
     .font('Helvetica')
     .text(`Generated: ${esgReport.report_generated_at || new Date().toISOString()}`, { align: 'center' })
     .text(`Overall ESG Rating: ${esgReport.overall_esg_rating || 'N/A'}`, { align: 'center' })
     .moveDown(2);
}

/**
 * Generates PDF report buffer
 * @param {object} baseData - Base factory data
 * @param {object} analysis - Complete analysis results
 * @returns {Promise<Buffer>}
 */
function generatePDFReport(baseData, analysis) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
      });

      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const esgReport = analysis.esg_report || {};

      addReportHeader(doc, esgReport);

      addSectionHeading(doc, 'Executive Summary');
      addSectionContent(doc, esgReport.executive_summary);

      addSectionHeading(doc, 'Environmental Performance');
      addSectionContent(doc, esgReport.environmental_performance);

      addSectionHeading(doc, 'Risk & Compliance');
      addSectionContent(doc, esgReport.risk_and_compliance);

      addSectionHeading(doc, 'Optimization Strategy');
      addSectionContent(doc, esgReport.optimization_strategy);

      addSectionHeading(doc, 'Financial Impact Summary');
      addSectionContent(doc, esgReport.financial_impact_summary);

      addSectionHeading(doc, 'Forward Outlook');
      addSectionContent(doc, esgReport.forward_outlook);

      doc.fontSize(8)
         .font('Helvetica')
         .text('This report is generated by Carbon Intelligence Platform.', { align: 'center' })
         .moveDown(0.3)
         .text('Confidential - For Internal Use Only', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = {
  generatePDFReport
};
